version: '3.8'

services:

  app1:
    build:
      context: .
      args:
        NEXT_PUBLIC_MIDTRANS_CLIENT_KEY: ${NEXT_PUBLIC_MIDTRANS_CLIENT_KEY}
    container_name: qurban_app_1
    ports:
      - "80:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - qurban_network

networks:
  qurban_network:
    external: false