version: '3.8'

services:

  app1:
    build:
      context: .
      args:
        NEXT_PUBLIC_MIDTRANS_CLIENT_KEY: ${NEXT_PUBLIC_MIDTRANS_CLIENT_KEY}
    container_name: qurban_app_1
    expose:
      - "3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - qurban_network

  app2:
    build:
      context: .
      args:
        NEXT_PUBLIC_MIDTRANS_CLIENT_KEY: ${NEXT_PUBLIC_MIDTRANS_CLIENT_KEY}
    container_name: qurban_app_2
    expose:
      - "3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - qurban_network

  nginx:
    image: nginx:alpine
    container_name: qurban_nginx
    ports:
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    restart: unless-stopped
    networks:
      - qurban_network

networks:
  qurban_network:
    external: false