name: CI/CD Pipeline Qurban Story
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Jalankan Deployment via Native SSH
        run: |
          if command -v apk >/dev/null; then
            apk add --no-cache openssh-client sshpass
          elif command -v apt-get >/dev/null; then
            apt-get update && apt-get install -y openssh-client sshpass
          fi

          export SSHPASS="${{ secrets.SSH_PASSWORD }}"
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@172.17.0.1 << 'EOF'
            cd /var/www/qurban-story
            if [ ! -d ".git" ]; then
              git clone http://10.0.2.15:3000/qurbanstory/qurban-story.git .
            else
              git pull origin main
            fi
            docker compose up -d --build
          EOF